name: Canary Release

on:
  push:
    branches:
      - main
    tags-ignore:
      - 'v*'
  workflow_dispatch:

jobs:
  canary-release:
    # Skip if commit message contains [skip ci] or starts with "chore: release"
    if: |
      !contains(github.event.head_commit.message, '[skip ci]') &&
      !startsWith(github.event.head_commit.message, 'chore: release')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test

      - name: Run typecheck
        run: bun run typecheck

      - name: Build
        run: bun run build

      - name: Configure npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm whoami

      - name: Generate canary version
        id: canary
        run: |
          # Get the current version from package.json
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          
          # Generate canary version: current-canary.shortSHA.timestamp
          SHORT_SHA=$(git rev-parse --short HEAD)
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          CANARY_VERSION="${CURRENT_VERSION}-canary.${SHORT_SHA}.${TIMESTAMP}"
          
          echo "version=${CANARY_VERSION}" >> $GITHUB_OUTPUT
          echo "Generated canary version: ${CANARY_VERSION}"

      - name: Update package version
        run: |
          npm version ${{ steps.canary.outputs.version }} --no-git-tag-version

      - name: Publish canary
        run: |
          npm publish --tag canary --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create deployment summary
        run: |
          echo "## 🚀 Canary Release Published" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Version:** \`${{ steps.canary.outputs.version }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Install:** \`npm install @atomic-ehr/fhir-canonical-manager@canary\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Commit:** [\`${{ github.sha }}\`](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})" >> $GITHUB_STEP_SUMMARY